#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xD55D978A8A1420E4 (coreteam@netfilter.org)
#
Name     : conntrack-tools
Version  : 1.4.8
Release  : 18
URL      : https://www.netfilter.org/projects/conntrack-tools/files/conntrack-tools-1.4.8.tar.xz
Source0  : https://www.netfilter.org/projects/conntrack-tools/files/conntrack-tools-1.4.8.tar.xz
Source1  : https://www.netfilter.org/projects/conntrack-tools/files/conntrack-tools-1.4.8.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: conntrack-tools-bin = %{version}-%{release}
Requires: conntrack-tools-lib = %{version}-%{release}
Requires: conntrack-tools-license = %{version}-%{release}
Requires: conntrack-tools-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnetfilter_conntrack)
BuildRequires : pkgconfig(libnetfilter_cthelper)
BuildRequires : pkgconfig(libnetfilter_cttimeout)
BuildRequires : pkgconfig(libnetfilter_queue)
BuildRequires : pkgconfig(libnfnetlink)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libtirpc)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
= Setting up active-active load-sharing hash-based stateful firewall =
by Pablo Neira Ayuso <pablo@netfilter.org> in 2010

%package bin
Summary: bin components for the conntrack-tools package.
Group: Binaries
Requires: conntrack-tools-license = %{version}-%{release}

%description bin
bin components for the conntrack-tools package.


%package lib
Summary: lib components for the conntrack-tools package.
Group: Libraries
Requires: conntrack-tools-license = %{version}-%{release}

%description lib
lib components for the conntrack-tools package.


%package license
Summary: license components for the conntrack-tools package.
Group: Default

%description license
license components for the conntrack-tools package.


%package man
Summary: man components for the conntrack-tools package.
Group: Default

%description man
man components for the conntrack-tools package.


%prep
%setup -q -n conntrack-tools-1.4.8
cd %{_builddir}/conntrack-tools-1.4.8
pushd ..
cp -a conntrack-tools-1.4.8 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696358608
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1696358608
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/conntrack-tools
cp %{_builddir}/conntrack-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/conntrack-tools/075d599585584bb0e4b526f5c40cb6b17e0da35a || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/conntrack
/V3/usr/bin/conntrackd
/V3/usr/bin/nfct
/usr/bin/conntrack
/usr/bin/conntrackd
/usr/bin/nfct

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/conntrack-tools/ct_helper_amanda.so
/V3/usr/lib64/conntrack-tools/ct_helper_dhcpv6.so
/V3/usr/lib64/conntrack-tools/ct_helper_ftp.so
/V3/usr/lib64/conntrack-tools/ct_helper_mdns.so
/V3/usr/lib64/conntrack-tools/ct_helper_rpc.so
/V3/usr/lib64/conntrack-tools/ct_helper_sane.so
/V3/usr/lib64/conntrack-tools/ct_helper_slp.so
/V3/usr/lib64/conntrack-tools/ct_helper_ssdp.so
/V3/usr/lib64/conntrack-tools/ct_helper_tftp.so
/V3/usr/lib64/conntrack-tools/ct_helper_tns.so
/usr/lib64/conntrack-tools/ct_helper_amanda.so
/usr/lib64/conntrack-tools/ct_helper_dhcpv6.so
/usr/lib64/conntrack-tools/ct_helper_ftp.so
/usr/lib64/conntrack-tools/ct_helper_mdns.so
/usr/lib64/conntrack-tools/ct_helper_rpc.so
/usr/lib64/conntrack-tools/ct_helper_sane.so
/usr/lib64/conntrack-tools/ct_helper_slp.so
/usr/lib64/conntrack-tools/ct_helper_ssdp.so
/usr/lib64/conntrack-tools/ct_helper_tftp.so
/usr/lib64/conntrack-tools/ct_helper_tns.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/conntrack-tools/075d599585584bb0e4b526f5c40cb6b17e0da35a

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/conntrackd.conf.5
/usr/share/man/man8/conntrack.8
/usr/share/man/man8/conntrackd.8
/usr/share/man/man8/nfct.8
